const GET_QUESTIONS = 'GET_QUESTIONS'
const GETTING_QUESTIONS = 'GETTING_QUESTIONS'
const GETTING_QUESTIONS_SUCCESS = 'GETTING_QUESTIONS_SUCCESS'
const GETTING_QUESTIONS_FAILURE = 'GETTING_QUESTIONS_FAILURE'
const INPUT_ANSWER = 'INPUT_ANSWER'
const SUBMIT_ANSWER = 'SUBMIT_ANSWER'
const SUBMITTING_ANSWER = 'SUBMITTING_ANSWER'
const COMPLETED_QNS = 'COMPLETED_QNS'

export default { 
    GET_QUESTIONS, 
    GETTING_QUESTIONS, 
    GETTING_QUESTIONS_FAILURE, 
    GETTING_QUESTIONS_SUCCESS,
    INPUT_ANSWER,
    SUBMIT_ANSWER,
    SUBMITTING_ANSWER,
    COMPLETED_QNS
}